## KNN : k-최근접 이웃 분류 (k-Nearest neighbor)

In [1]:
import numpy as np

In [11]:
# 키, 학생분류
x = [140, 150, 160, 170, 180]
y = [0, 0, 1, 1, 2] # 초:0, 중:1, 고: 2
x_test = [120, 158, 177] 

In [17]:
x = np.array(x).reshape((-1, 1)) # 1d 를 2d 로 모양 변경, -1: 자동
x_test = np.array(x_test).reshape((-1, 1))
y = np.array(y)
x.shape

(5, 1)

In [13]:
from sklearn.neighbors import KNeighborsClassifier # 대문자로 시작하면 클래스입니다

In [ ]:
model = KNeighborsClassifier(n_neighbors=1) # 객체 만들기 , shift+tab 설명
model #객체 정보 보자

In [36]:
model.fit(x, y)# 모델을 핏팅해라

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [37]:
model.predict(x_test) #예측해라 

array([0, 2])

In [41]:
# 동물분류 새0, 개1, 말2
# 특징 [다리 갯수, 털 길이 cm]

x = [[2, 7.0], [2, 4.0], [4, 10], [4, 9], [4, 3], [4, 5.0]]
y = [0, 0, 1, 1, 2,2] 
x_test = [[2, 9], [4, 4]] 

위 x,y 데이터로 KNN 모델을 fit 해서 x_test 를 예측하세요

In [43]:
model = KNeighborsClassifier(n_neighbors=1).fit(x,y)
model.predict(x_test)

array([0, 2])

reshape 연습 

In [23]:
a = np.arange(9)
a, a.shape, a.ndim #n : number

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), (9,), 1)

In [32]:
np.reshape(a, (-1, 1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])