키 데이터 파일을 읽어서 KNN 분류기를 이용해서 테스트 셋을 예측해봅니다

# https://github.com/sogangori/choongang20

In [76]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsRegressor

In [77]:
df = pd.read_csv('../height.csv')
df.shape

(6, 3)

In [78]:
x_test = [[166, 182], [155,177]] # 이 데이터의 자식의 키를 KNN 으로 예측하세요

In [79]:
x = df[['mother','father']]
y = df['child']

In [80]:
# 넘파이로 변경
#x = x.values
x = np.array(x)
y = np.array(y)

In [81]:
# k 하이퍼파라미터 : 학습되지 않고 사람이 정해주는 값
model = KNeighborsRegressor(n_neighbors=2).fit(x,y) # KNN 예측기
model.predict(x_test) # 가장 가까운 k 의 평균값 

array([ 168. ,  163.5])

선형 함수를 이용하는 선형 모델로 학습시켜서 테스트셋의 자식 키를 예측해봅시다

- y = ax + b
- y : 자식의 키, x : [어머니 키, 아버지 키] = [ x0 , x1]
- y = w0 * x0 + w1 * x1 + b
- 자식의 키 = w0 * 어머니 키 + w1 * 아버지 키 + b
- w0 = 0.4, w1=0.6, b = 3 가정해보면
- 자식의 키 = 0.4 * 어머니 키 + 0.6 * 아버지 키 + 3(세대간의 평균 키 차이)

In [82]:
from sklearn.linear_model import LinearRegression

In [83]:
model = LinearRegression()

In [84]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

y = w0 * x0 + w1 * x1 + b
y = -2 * x0 + 3 * x1 - 18

In [85]:
model.coef_, model.intercept_ # 계수와 절편 weight, bias

(array([-1.98982068,  2.95274309]), -18.913505355979879)

In [89]:
# y = w0 * x0 + w1 * x1 + b
h = np.sum(model.coef_ * x, axis=1, keepdims=True) + model.intercept_
h

array([[ 164.68151151],
       [ 193.953039  ],
       [ 162.81964254],
       [ 171.48594425],
       [ 163.7185891 ],
       [ 168.3412736 ]])

In [87]:
y

array([172, 195, 167, 166, 155, 170], dtype=int64)

성능 측정, 
- 오차가 얼마나 나느냐?

In [96]:
#절대값 오차 평균 : L1 loss 
np.mean(np.abs(np.squeeze(h) - y)) # squeeze ((즙을) 짜다) 차원이 1이면 제거, 

4.7348444497050748

In [99]:
#metric 지표
from sklearn.metrics import mean_absolute_error # 평균 절대 오차
from sklearn.metrics import r2_score # 결정계수, 1: 완벽, 0:보통, 음수: 엉망

In [100]:
mean_absolute_error(y, h), r2_score(y, h) # 0.79 는 1 에 가까우므로 예측이 잘됐다고 볼 수 있다 

(4.7348444497050748, 0.79311197212233209)