### 분류 classification

클래스가 2개 뿐인 2진(binary) 분류를 해봅시다, 0,1 분류 

1 : 관심 타겟 (더 적은 샘플)
0 : 관심 없는 클래스 (더 흔하고 많은 샘플)

암환자 분류 : 0:정상 1:암환자
사기 검출 : 0:정상 1:사기
생존자:1, 사망자:0

In [2]:
import numpy as np

목표: 혈액형 예측하기 (A, B)
A 의 특징 : 배려심 있다, 막연한 걱정
B 의 특징 : 용기, 기분파다

In [ ]:
판단력, 사회성

In [3]:
#[판단력, 사회성]
x = [[50, 90], [80, 50]]
y = [0, 1]

In [5]:
x = np.array(x)
y = np.array(y)

In [8]:
from sklearn.linear_model import LogisticRegression #논리 회귀 = 선형 회귀 + sigmoid

In [10]:
model = LogisticRegression().fit(x, y) # 학습 

In [11]:
model.predict(x)

array([0, 1])

In [13]:
# y = w0 * x0 + w1 * x1 + b
model.coef_, model.intercept_

(array([[ 0.16068743, -0.1498761 ]]), array([ 0.0004109]))

In [15]:
x

array([[50, 90],
       [80, 50]])

In [18]:
# B 형이냐 ?  (B형이 클래스 1 이므로)
np.sum(model.coef_ * x + model.intercept_, axis=1) > 0 # 가로방향의 값을 더하기 

array([False,  True], dtype=bool)

In [19]:
from sklearn.datasets import load_iris # 붓꽃 데이터

In [20]:
x, y = load_iris(True)

In [21]:
x.shape, y.shape

((150, 4), (150,))

In [24]:
x = x[:100]
y = y[:100]

In [27]:
model = LogisticRegression().fit(x, y) 

In [29]:
model.score(x, y)

1.0

In [30]:
model.coef_, model.intercept_

(array([[-0.40731745, -1.46092371,  2.24004724,  1.00841492]]),
 array([-0.26048137]))

In [37]:
# 마지막으로 0보다 크냐(후처리) 로 최종 판정을 내린다
np.sum(model.coef_ * x + model.intercept_, axis=1) > 0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)